webtalk_init -webtalk_dir C:/Users/zachz/OneDrive/Documents/GitHub/Senior-Design/Reed-Solomon-ECC/Reed-Solomon-ECC.sim/sim_1/behav/xsim/xsim.dir/tb_RS_Decoder_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Mar 29 14:43:34 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7e923944-4ecf-44ae-8805-3e49ed515deb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "118ad12101f74ed48060e773050ffc42" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1498 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "16" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "124 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "102 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "1348" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "537" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.70_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "81760_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4293071234 -regid "" -xml C:/Users/zachz/OneDrive/Documents/GitHub/Senior-Design/Reed-Solomon-ECC/Reed-Solomon-ECC.sim/sim_1/behav/xsim/xsim.dir/tb_RS_Decoder_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/zachz/OneDrive/Documents/GitHub/Senior-Design/Reed-Solomon-ECC/Reed-Solomon-ECC.sim/sim_1/behav/xsim/xsim.dir/tb_RS_Decoder_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/zachz/OneDrive/Documents/GitHub/Senior-Design/Reed-Solomon-ECC/Reed-Solomon-ECC.sim/sim_1/behav/xsim/xsim.dir/tb_RS_Decoder_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
